### PR TITLE
Fix progress with patterns and backup discovery

### LINKED ISSUE #298: --discover-backup not working as advertised, looks for files even if they weren't found
I noticed that without the `--discover-backup` flag, I had 800k requests lined up in the progress bar, but with the `--discover-backup` option, I had ~6 million. Reading the help text, it says that backup files are only enumerated if a file is found. Given that, wouldn't it make sense to display only the 800k requests in the progress bar, and update the amount of requests when files get found?

I'm using Kali's version of gobuster.

```
└─$ gobuster version               
3.1.0
```

I initially thought the progress bar would maybe jump to 100% when all 800k requests have been completed without a single found file.

However, after playing around with it, it seems the help text is wrong. `--discover-backup` will search for files even if they haven't been found.

Proof: (look at the time stamps and how long it took to run the scans - 3 seconds vs 20 seconds)

```
┌──(x90slide㉿kali)-[~/…/jeeves/testing/autorecon/scans]
└─$ gobuster dir -u http://jeeves.htb:80/ -w /tmp/small.txt --discover-backup --no-tls-validation --status-codes "200,204,301,302,307,403,500" | tee "/tmp/tcp_80_http_gobuster_words_combined.txt"        
===============================================================
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     http://jeeves.htb:80/
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                /tmp/small.txt
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.1.0
[+] Timeout:                 10s
===============================================================
2021/06/17 18:25:38 Starting gobuster in directory enumeration mode
===============================================================
                              
===============================================================
2021/06/17 18:25:58 Finished
===============================================================
┌──(x90slide㉿kali)-[~/…/jeeves/testing/autorecon/scans]
└─$ gobuster dir -u http://jeeves.htb:80/ -w /tmp/small.txt  --no-tls-validation --status-codes "200,204,301,302,307,403,500" | tee "/tmp/tcp_80_http_gobuster_words_combined.txt"     
===============================================================
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     http://jeeves.htb:80/
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                /tmp/small.txt
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.1.0
[+] Timeout:                 10s
===============================================================
2021/06/17 18:26:12 Starting gobuster in directory enumeration mode
===============================================================
                            
===============================================================
2021/06/17 18:26:15 Finished
===============================================================

```

The help entry says:

```
 -d, --discover-backup                 Upon finding a file search for backup files
```

Given that not a single file was found, I would have expected the directory enumeration to take the same amount of time on both occasions.

### PR DESCRIPTION
**Pull request by acammack**
Hi all, this resolves the issues where patterns were not counted towards possible attempts, file extension searching was not applied to patterns in `GobusterDir`, and backups were being brute-forced for the entire wordlist. These all had pretty tangled fixes so I lumped them into this PR.

```
$  ./gobuster dir -p patterns.txt -w testwords.txt -x .php,.html -db -u https://testing.test
===============================================================
Gobuster v3.7
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     https://testing.test
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                testwords.txt
[+] Patterns:                patterns.txt (2 entries)
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.7
[+] Extensions:              php,html
[+] Timeout:                 10s
===============================================================
Starting gobuster in directory enumeration mode
===============================================================
/index.html           (Status: 200) [Size: 179]
/index.html.bak       (Status: 200) [Size: 179]
Progress: 33 / 33 (100.00%)
===============================================================
Finished
===============================================================
$ wc -l testwords.txt patterns.txt 
 3 testwords.txt
 3 patterns.txt
 5 total
```

Note the 33 total attempts for:

```
3 words * 3 patterns * (2 file extensions + no file extension) = 27 original attempts
plus 6 backup styles for the original find of "index.html"
```

~Since it's in this wheelhouse, I'm open to also changing the pattern generation and wordlist behavior to either have a flag for the exclusion of the bare words from the wordlist that's either on or off by default or even make patterns always supersede the wordlist and make users add a plain `{GOBUSTER}` pattern if they want the original word in addition to the patterns. I'm not sure which would be the most useful, though.~

Looking through the old issues, it seems that (1) filtering the whole wordlist through the patterns and (2) applying the discovery patterns exactly once would be the most consistent behavior.

Fixes #298, #405, #480, #533, #319, #364

There are still a couple of things to do before this is ready, but I wanted to get this open for some eyes:
- [x]  I need to track successes from success pattern generation to keep it from infinitely generating requests against malicious services/with misconfiguration, possibly with a configurable chain generation limit
- [x] I want to add a global flag for post-find pattern expansion, so that if the user desired everything could be checked with patterns after a successful find

### CODE REVIEW

**Comment by firefart** [comment]
Nice thanks already! One thing I noticed is that we should close all channels when we are done sending on them

**Comment by acammack** [comment]
> One thing I noticed is that we should close all channels when we are done sending on them

Hmm, is that necessary here?  By the time we would `close` the `wordChan` and `moreWordsChan` channels, all the other goroutines referring to them will have finished and `close` won't have anyone to notify. The resources for the channels still won't be freed up until after `Run()` returns either way. I guess it wouldn't hurt anything either, but I feel it would muddy the intent of the code by implying that there might be consumers that need to be notified that the channels are done.

**Comment by acammack** [comment]
Yes, all the producers and consumers are terminated by contexts now and verified with wait groups and request counts. I think this also fixes a few minor issues that have already been closed, like #541

**Comment by firefart** [comment]
Awesome, so just put the PR from draft to normal once you are ready so I can have a test. Thanks so far!

**Comment by acammack** [comment]
This should be good to test. I think the changes in here will help with adding machine readable results and a pause/state file, though I'll leave those to the future. I think we could also make our string manipulation more efficient, but that's also another PR.

File: libgobuster/libgobuster.go [hunk 1]
```diff
@@ -41,33 +52,40 @@ func NewGobuster(opts *Options, plugin GobusterPlugin, logger *Logger) (*Gobuste
 	return &g, nil
 }
 
-func (g *Gobuster) worker(ctx context.Context, wordChan <-chan string, wg *sync.WaitGroup) {
+func (g *Gobuster) worker(ctx context.Context, guessChan <-chan *Guess, successChan chan<- *Guess, wg *sync.WaitGroup) {
 	defer wg.Done()
 	for {
+		// Prioritize stopping when the context is done
 		select {
```
Comment (firefart) [inline libgobuster/libgobuster.go:59]: I think this select is not necessary as the context is handled in the below select?

File: libgobuster/libgobuster.go [hunk 2]
```diff
@@ -76,10 +94,93 @@ func (g *Gobuster) worker(ctx context.Context, wordChan <-chan string, wg *sync.
...
+			// Skip empty lines removing expected work
+			g.Progress.IncrementTotalRequests(-1 * wordlist.guessesPerLine)
+			continue
+		}
+
+		if len(g.Opts.Patterns) > 0 {
+			for _, w := range g.processPatterns(word) {
+				guess := &Guess{word: w, discoverOnSuccess: true}
+				select {
+				case <-ctx.Done():
```
Comment (firefart) [inline libgobuster/libgobuster.go:150]: I think this select is also not necessary

File: libgobuster/libgobuster.go [hunk 3]
```diff
@@ -143,56 +234,81 @@ func (g *Gobuster) Run(ctx context.Context) error {
...
+	feederGroup.Add(1)
+	go g.feedWordlist(feederCtx, guessChan, wordlist, &feederGroup)
 
-Scan:
-	for scanner.Scan() {
+ListenForMore:
+	for {
+		// Prioritize stopping when the context is done
 		select {
 		case <-ctx.Done():
```
Comment (firefart) [inline libgobuster/libgobuster.go:266]: I think this select is also not necessary

File: libgobuster/libgobuster.go (hunk 1 above)
Comment (acammack) [reply libgobuster/libgobuster.go:59]: In the Go spec, `select` is specified as:

> If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection.

So while `<-ctx.Done()` worked as an escape-hatch to blocking writes using just one `select` statement, there are internal states that would lead to more work being queued up and executed than anticipated, with the work potentially being unbounded. This is made more likely with our use of buffered channels. The only way to prioritize select clauses is with extra tiers of `select`, and we need duplicate `<-ctx.Done()`s in each `select` so that we don't end up blocking on a channel write. While lacking deterministic shutdown wasn't a huge problem with the existing code, it will be handy for implementing pause/restart.

Comment (firefart) [reply libgobuster/libgobuster.go:59]: yes but you have an empty select that returns on a context done or continues. In the following select you also check for a done context so the previous select is not necessary as there are no operations between the context checks

Comment (acammack) [reply libgobuster/libgobuster.go:59]: The catch is the second `select` won't always choose `ctx.Done()` if there are guesses buffered in `guessChan`, it's a coin flip if both channels are available for reading. Consider the following program:
```go
package main

import "fmt"

func main() {
        ones := make(chan int, 10)
        twos := make(chan int, 10)

        for range 10 {
                ones <- 1
                twos <- 2
        }

        for range 20 {
                select {
                case <-ones:
                        fmt.Println("Got a one!")
                case <-twos:
                        fmt.Println("Got a two!")
                }
        }
}
```
It's output is something like:
```
$ go run simultaneous_receives.go 
Got a two!
Got a two!
Got a two!
Got a two!
Got a one!
Got a one!
Got a two!
Got a one!
Got a two!
Got a one!
Got a two!
Got a two!
Got a two!
Got a two!
Got a one!
Got a one!
Got a one!
Got a one!
Got a one!
Got a one!
```

Comment (firefart) [reply libgobuster/libgobuster.go:59]: thanks for the clarification ! missed that it’s just a single select

**Comment by firefart** [comment]
Thanks! Will test it on the dev branch with the other changes that are staged for the next version
